# Generated by Django 3.2.9 on 2021-11-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district',
            new_name='name',
        ),
    ]
