# Generated by Django 3.2.9 on 2021-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_dailytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='do_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='working_status',
            field=models.BooleanField(default=False),
        ),
    ]
