# Generated by Django 3.2.9 on 2021-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_auto_20211126_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
