# Generated by Django 3.2.9 on 2021-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0007_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='u_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
