# Generated by Django 3.2.9 on 2021-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_employee_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='u_id',
            new_name='user_id',
        ),
    ]
