# Generated by Django 3.2.9 on 2021-12-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0010_auto_20211203_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='employee_id',
        ),
    ]
