# Generated by Django 3.2.9 on 2021-12-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0013_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='m_date',
            new_name='meeting_date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='m_time',
            new_name='meeting_time',
        ),
    ]
