# Generated by Django 3.2.9 on 2022-01-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0015_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
