# Generated by Django 3.2.9 on 2022-01-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0017_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='attend_time',
        ),
    ]
