# Generated by Django 3.2.9 on 2022-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0018_remove_attendence_attend_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('client_id', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='media/images')),
                ('phone', models.CharField(max_length=150)),
            ],
        ),
    ]
