# Generated by Django 3.2.9 on 2022-01-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0019_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='client_name',
        ),
    ]
